apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: {{ .Values.app.name }}
  name: {{ .Values.app.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
      - image: {{ .Values.app.name }}:1.0.0
        name: {{ .Values.app.name }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources: {}
        env:
        - name: PYTHONUNBUFFERED
          value: "1"

status: {}